### ISSUE TITLE
Test Integration BBB not opening any meetings

### ISSUE THREAD

**Issue by cyamal1b4** [blindsidenetworks/mattermost-plugin-bigbluebutton#103]
I've set up the Mattermost server in docker (production install not local test) and went through the correct steps to get the BBB plug-in integrated. However, when I select to call someone (a test user on another machine) it wont open any BBB services. It just creates a private chat but wont pivot into any meetings or the BBB application.

**Comment by iddelacruz** [comment]
Hi, you fixed this problem? I have a problem with my bbb plugin and my bbb server with Google oauth

**Comment by harshilsharma63** [comment]
@cyamal1b4 @iddelacruz this bug was resolved the in the latest plugin release. I recommend you upgrade to the latest release.

Do let me know if you still face the issue.

**Comment by harshilsharma63** [comment]
@iddelacruz I'm closing this issue for now. Feel free to re-open if you still encounter the bug.
