### ISSUE TITLE
student URL

### ISSUE THREAD

**Issue by tclavier** [blindsidenetworks/mattermost-plugin-bigbluebutton#110]
As a teacher, my students are in one mattermost channel. I want to create a BBB room and share the student url (with a token for student) in the mattermost channel and I want to have the teacher URL (actual url with teacher token) in a private channel with bot.

**Comment by harshilsharma63** [comment]
@tclavier we recently added the feature that makes sure only the meeting creator becomes the meeting moderator (see screenshot below)

<img width="761" alt="Screenshot 2020-12-05 at 6 49 52 PM" src="https://user-images.githubusercontent.com/18575143/101244139-ab7a3880-372a-11eb-9654-16622c53b5e0.png">

With this feature, I think it will work for you if you created the BBB meeting directly in the channel where all your students are.

Do let me know if this doesn't work for your scenerio.

**Comment by tclavier** [comment]
I will test, but i thinks that will close this issue :-)

**Comment by harshilsharma63** [comment]
@tclavier 👍

**Comment by harshilsharma63** [comment]
@tclavier I'm closing this issue for now as the new feature resolves it. Feel free to re-open if you face any issue with the plugin using that feature.
