### ISSUE TITLE
getRecordings is spamming our scalelite API server

### ISSUE THREAD

**Issue by moschlar** [blindsidenetworks/mattermost-plugin-bigbluebutton#113]
Hi,
we noticed that our scalelite API gets hammered with requests for recordings by this plugin.
The plugin has 1262 meetings stored in the recording_queue key while there are only 1118 meetings in all_meetings.

That doesn't seem right.
What can be done to prevent this or clean this up?

Regards,
Moritz

**Comment by harshilsharma63** [comment]
@moschlar are you on the latest plugin version? This bug where the plugin keeps checking for meetings was fixed in the latest release.

**Comment by moschlar** [comment]
Yes, we do!

You probably mean this commit: https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/commit/14a66db06596f66514695382971b5e14e4ca726d right?

But I actually can't see any changes in the code that would correlate with this problem!

**Comment by harshilsharma63** [comment]
@moschlar this is the commit for the bug fix - https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/commit/965fb1fd75e9e12e0250b50fb0617d58ca885842

**Comment by moschlar** [comment]
I've just seen #100 - that seems highly relevant to our issue!
