### ISSUE TITLE
Update to 2.2.26 latest release oficial BBB

### ISSUE THREAD

**Issue by NexusEFR** [blindsidenetworks/mattermost-plugin-bigbluebutton#114]
an update is planned for the MM plugin just like the official version of BBB, it seems to have more development than the plugin. Thank you, fantastic plugin nonetheless.
Best regards

**Comment by moschlar** [comment]
?

**Comment by NexusEFR** [comment]
The official version already goes for 2.2.26 but in Mattermost it is 2.1.0, then the question is... will you also update the plugin for Mattermost with this latest version? Thank you, greetings

**Comment by moschlar** [comment]
The version of the plugin is not tied to the version of BigBlueButton.

**Comment by harshilsharma63** [comment]
@NexusEFR @moschlar is right. The plugin version and BBB version are not dependent. You can use Mattermost plugin version 2.1.0 with BBB version 2.2.26. Though I recommend upgrading to the latest version of Mattermost plugin.
