### ISSUE TITLE
Single Sign On in BigBlueButton Server 404 NotFound

### ISSUE THREAD

**Issue by iddelacruz** [blindsidenetworks/mattermost-plugin-bigbluebutton#115]
Hi guys.

I'm testing this plugin with my own biblugebutton server. My server have SSO with google and when iI try to create a meeting from Mattermost and access to the meeting URL, I have those message:

**Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Wed Nov 04 11:40:06 UTC 2020
There was an unexpected error (type=Not Found, status=404).
No message available**

I would like to know how to fix this and which changes I need to do, couse this problem is for the Single Sign On config

**Comment by harshilsharma63** [comment]
@iddelacruz you should be able to see some error on either the Mattermost side or the BBB side. Can you share what error you're getting in those logs?

**Comment by harshilsharma63** [comment]
@iddelacruz I'm closing this one for now and this is an issue on BBB server-side, not on the Mattermost plugin.
