### ISSUE TITLE
BBB mattermost plugin redirects to https://blindsidenetworks.com/

### ISSUE THREAD

**Issue by BlackHawk171** [blindsidenetworks/mattermost-plugin-bigbluebutton#118]
BBB mattermost plugin redirects to https://blindsidenetworks.com/ when trying to connect with meeting

EDIT: After several browser refreshes it opens the meeting, but this is annoying

**Comment by BlackHawk171** [comment]
Saw Issue from April, but it seems it is not fixed yet

**Comment by harshilsharma63** [comment]
@BlackHawk171 are you facing the issue on the latest plugin release?

**Comment by ahmaddanialmohd** [comment]
Hello, @harshilsharma63 

Another user just reported this on the [Mattermost Forum](https://forum.mattermost.org/t/bigbluebutton-sends-data-to-blindsidenetworks/10788/3) as well.

I'll double confirm the version that the affected user is on.

**Comment by ahmaddanialmohd** [comment]
> Hello, @harshilsharma63
> 
> Another user just reported this on the [Mattermost Forum](https://forum.mattermost.org/t/bigbluebutton-sends-data-to-blindsidenetworks/10788/3) as well.
> 
> I'll double confirm the version that the affected user is on.

Hello, team. I would like to update that the version of Mattermost Server is 5.25.2 and the version of the plugin is 2.1.0.

**Comment by harshilsharma63** [comment]
@ahmaddanialmohd please upgrade to Mattermost plugin v2.2.0. This issue was already resolved.

**Comment by harshilsharma63** [comment]
@ahmaddanialmohd I'm closing this issue for now. If you still face this with plugin version v2.2.0, feel free to re-open.
