### ISSUE TITLE
Use ServiceSettings.SiteUrl setting in config.json for the callback URL

### ISSUE THREAD

**Issue by jasonblais** [blindsidenetworks/mattermost-plugin-bigbluebutton#12]
To configure BigBlueButton, the Mattermost System Admin needs to enter the Mattermost Site URL. This is used for the callback URL to notify Mattermost when the meeting has ended.

![image](https://user-images.githubusercontent.com/13119842/45558771-b1fcfc80-b80e-11e8-81f8-7af24af8bc38.png)

Given the admin would have already configured their Site URL via ServiceSettings.SiteUrl setting in config.json, this additional setting may not be necessary.

Hence, the proposal is to use the config.json setting instead, and remove the Site URL setting from the BigBlueButton plugin.

We may need to consider what the experience is if the admin has not configured their Site URL in config.json.

**Comment by ffdixon** [comment]
@jasonblais Good suggestion.

**Comment by ypgao1** [comment]
Completed. For future developers, the way a plugin references the config.json file is through `p.API.GetConfig()`

ie, the SiteURL will be: `p.API.GetConfig().ServiceSettings.SiteURL`

Also, for the case when the admin has not configured the Site URL, we are preventing the creation of meetings and sending an ephemeral message "Please provide a 'Site URL' in Settings > General > Configuration". (An alternative approach would be still enabling Meeting creations but limit the features to those that do not require the Site URL information. )

**Comment by jasonblais** [comment]
Covered by https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/pull/14
