### ISSUE TITLE
Add Name Text Field and Logo URL for Branding 

### ISSUE THREAD

**Issue by palmtown** [blindsidenetworks/mattermost-plugin-bigbluebutton#120]
Hello,

You've done a great job creating this plugin.  However, I'd like to kindly request a feature for branding.  In short, this would take 2 new fields, one field be added to the plugin settings page named "Plugin Name," and other would be "Plugin Logo."  The Plugin Name field should should default to "BigBlueButton" however, when changed should be reflected in the bot name, the "Create a BigBlueButton Meeting" link and other places where the plugin post messages etc. that includes BigBlueButton.  

Next, the plugin logo URL should replace the existing logo you have statically coded https://pbs.twimg.com/profile_images/467451035837923328/JxPpOTL6_400x400.jpeg.  However, that URL should be default.  

This feature request would make the plugin brandable.

**Comment by harshilsharma63** [comment]
@palmtown Thanks for the feature request. Unfortunately, this is outside the scope of this plugin. You should be able to update all those texts and images in your fork and build it. We'd be more than happy to assist if you face any problem in the build process.
