### ISSUE TITLE
'Start BBB Meeting' line sometimes not visible in user-profile popover 

### ISSUE THREAD

**Issue by H-B-Schmidt** [blindsidenetworks/mattermost-plugin-bigbluebutton#131]
Mattermost 5.30/5.31 - BBB Plugin 2.2.0

If I click on a username at the bottom of the screen for the first time, the user profile pop window is placed so that the 'Start BBB meeting' line is is not visible. If I click again the popup window is placed correctly.

This is true for both firefox and chrome so it seems to not be browser related. Not sure wether this is a BBB plugin or mattermost problem.

Expl.: Bad display after first click 
`<div id="user-profile-popover" role="tooltip" class="fade in user-profile-popover popover popover-sm popover-info right" style="display: block; top: 659px; left: 508.734px;">`

Expl: Good display after second click
`<div id="user-profile-popover" role="tooltip" class="fade in user-profile-popover popover popover-sm popover-info right" style="display: block; top: 625px; left: 508.734px;">`

**Comment by harshilsharma63** [comment]
@H-B-Schmidt if I got this right, you're referring to this issue -

<img width="364" alt="Screenshot 2021-05-30 at 5 35 42 PM" src="https://user-images.githubusercontent.com/18575143/120103492-772d8500-c16d-11eb-9831-98a015763a47.png">

If yes, this is a Mattermost issue and not a plugin issue. I'll look into it though.

**Comment by harshilsharma63** [comment]
@H-B-Schmidt can you share a GIF shows what's happening with your setup? I think the popup? I double checked and I see the popover correctly adjusting for viewport boundary.

**Comment by H-B-Schmidt** [comment]
I can't recreate it so it must have been fixed by some update.
