### ISSUE TITLE
Crash on 5.36.0 with CollapsedThread activated

### ISSUE THREAD

**Issue by jdauphant** [blindsidenetworks/mattermost-plugin-bigbluebutton#156]
If the threads panel is open, and I open a new left side pannel (like Recent Mentions
), I have this crash : (Mattermost app become blank)
![image](https://user-images.githubusercontent.com/1238254/122481935-eb6e8200-cfcf-11eb-800f-7bfa63924879.png)
I don't why the plugin is involved here.

How to reproduce :
1) active the collapsedthread beta fonctionnality in your personnal profil
2) open the new 'threads' panel
3) open "Recent Mentions" panel
4) wait 3-5 secondes

**Comment by harshilsharma63** [comment]
@jdauphant I;m successfully able to reproduce this bug. I'm looking into this.

**Comment by harshilsharma63** [comment]
@jdauphant this is fixed in v3.1.1 release - https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/releases/tag/v3.1.1

**Comment by jdauphant** [comment]
Thanks for your efficiency !

**Comment by jdauphant** [comment]
@harshilsharma63 I have tested the new release, I confirm that the bug is fixed on my setup !
Have a good day !

**Comment by harshilsharma63** [comment]
@jdauphant awesome!
