### ISSUE TITLE
New channel header icon looks weird

### ISSUE THREAD

**Issue by moschlar** [blindsidenetworks/mattermost-plugin-bigbluebutton#159]
It looks like some blue colored background is missing or something like that:

![Screenshot from 2021-07-06 13-42-16](https://user-images.githubusercontent.com/228095/124594405-4832bf00-de4f-11eb-8d29-69c8e8707725.png)

Don't know why. This is on Mattermost Version: 5.35.3

**Comment by moschlar** [comment]
Ah, it seems to be "optimised for dark mode" :-D

**Comment by harshilsharma63** [comment]
@moschlar This will be fixed this week. Thanks for reporting!

**Comment by harshilsharma63** [comment]
@moschlar this is fixed in [v3.2.1](https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/releases/tag/v3.2.1).
