### ISSUE TITLE
Maybe have two different "create meeting" options in the channel header menu

### ISSUE THREAD

**Issue by moschlar** [blindsidenetworks/mattermost-plugin-bigbluebutton#162]
One with recordings enabled (if the admin configured it to be allowed) and one explicitly with recordings disabled.
(This extends on my  suggestion in #161)

**Comment by moschlar** [comment]
See #82 also.

**Comment by harshilsharma63** [comment]
@moschlar I'm trying to understand its usecase and what problem it solves. Can you help?

**Comment by nough** [comment]
sometimes companies / meetings don't want even the chance that a meeting will be recorded. I think this would have to interact with the bigbluebutton backend to ensure that the files are not saved at all (as with conventional bbb recording functionality).

Use case 1: Company is holding a meeting where sensitive information is being discussed, that they do not want stored on a server. 

Use case 2: Company is holding a team meeting / technical presentation where they want to record the meeting.

**Comment by moschlar** [comment]
Maybe it would be ideally like this: there would be an advanced version of the `/bbb` command where you can change all settings that bbb offers (like Greenlight does with individual room settings) and the two we mentioned here just being "shortcuts" for the most often desired states of the recording toggle.

**Comment by nough** [comment]
Maybe, yes.

Unfortunately I think this issue isn't something that is currently possible
with the way that bigbluebutton is structured. It currently requires a
change to config files and a reload of the server to change this.

**Comment by harshilsharma63** [comment]
The meeting record settings are managed on a per-meeting basis on BBB. We can definitely have two buttons - one for allow and one for preventing recording. I'll work on this for v4.2

**Comment by nough** [comment]
Ah yes - I suppose you could prevent someone from clicking record using the
individual settings, but as far as I'm aware, if recording is on at the
server level, the meeting will still be saved to storage.

So an admin could still reprocess the recording, or a spook/crook could
gain access to the server and steal the "unrecorded" recording.

Admittedly this is probably outside of the realm of most users
requirements, and would only be necessary for the most security conscious
groups.

**Comment by harshilsharma63** [comment]
If such a user has gained access to your servers, you have bigger problems 😛

**Comment by nough** [comment]
I fully agree with the proposed solution.

> If such a user has gained access to your servers, you have bigger problems 😛

Oh of course. But from a "secure by design" perspective, why would you risk recording something that you definitely don't want to keep? It's just an added risk, which could combine with other procedural failures to lead to a loss of Confidentiality.

The background issue is the BBB architecture that records everything, which also wastes drive lifetime.

**Comment by moschlar** [comment]
@nough but since we now have the basic possibility of completely disabling recordings at all (5638c080ea143522fb2580db5a3b942644357ba1) the implementation for this issue would surely mirror that so that the meetings that are started without recording functionality aren't also recorded by BBB at all! :wink:

**Comment by nough** [comment]
Woah, I guess I've not been keeping up with the updates.

**Comment by harshilsharma63** [comment]
Upcoming changes sneak peek-

<img width="318" alt="Screenshot 2021-09-06 at 7 39 33 AM" src="https://user-images.githubusercontent.com/18575143/132150717-a8759a84-7ebf-4a08-915c-dff8cc0e0afc.png">

**Comment by moschlar** [comment]
@harshilsharma63 Can you add the built plugins to the assets for the release, please?
Thanks a lot!

**Comment by harshilsharma63** [comment]
@moschlar oops, I missed it. Added now.

**Comment by moschlar** [comment]
@harshilsharma63 No Problem! Thanks!
