### ISSUE TITLE
Version 4.0.1 has too many clicks to join a meeting

### ISSUE THREAD

**Issue by nough** [blindsidenetworks/mattermost-plugin-bigbluebutton#168]
In the latest full release of the plugin, users click "join meeting", and then get a private message (visible only to you) with the link to join the meeting. This adds an extra step and creates confusion for certain users, e.g.
- User 1 creates a meeting
- User 2 sends a long message
- User 3 clicks "join meeting", then doesn't realise they have to scroll down to get to the link.

**Comment by harshilsharma63** [comment]
Hmmm, I understand the pain point here. We cannot avoid the high level approach, which is click on a button to get the joining link, then open the joining link. But I have a few ideas about making the join link easy and quick to access. Let me try it out and I'll share the prototype here.

**Comment by nough** [comment]
Why was this implemented? Versions of the plugin before 4.0 don't require a
second click, they just join you to the meeting directly.

**Comment by harshilsharma63** [comment]
@nough it's needed for supporting Mattermost mobile app. Before v4 you weren't able to join meeting from the mobile app. Now you can.

**Comment by nough** [comment]
Ok, thanks for the update. We don't use the mobile app, so weren't aware of
the issue.

May I suggest an addition to the changelog that states the change?

**Comment by harshilsharma63** [comment]
No worries, mobile access was a huge demand :)

**Comment by harshilsharma63** [comment]
@nough the idea I had in mind doesn't work. For now, this is the best possible approach which covers desktop and mobile.
