### ISSUE TITLE
When Zoom and BigBlueButton (BBB) are both enabled, channel header dropdown for BBB appears in two lines

### ISSUE THREAD

**Issue by jasonblais** [blindsidenetworks/mattermost-plugin-bigbluebutton#17]
![image](https://user-images.githubusercontent.com/13119842/45949671-a4900100-bfca-11e8-91c8-3308522521e0.png)

![image](https://user-images.githubusercontent.com/13119842/45949674-aa85e200-bfca-11e8-9107-89c70a88e579.png)

**Comment by harshilsharma63** [comment]
Fixed icon's vertical alignment.

Before:
![](https://i.imgur.com/Pk8i7oZ.png) ![](https://i.imgur.com/KLtTVzH.png)

After:
![](https://i.imgur.com/6LXtcWh.png) ![](https://i.imgur.com/1fjwigd.png)

**Comment by jasonblais** [comment]
Thanks @harshilsharma63!

**Comment by harshilsharma63** [comment]
Closing as this has been resolved in v2.1.0.
