### ISSUE TITLE
connection error to bbb

### ISSUE THREAD

**Issue by cube48AG** [blindsidenetworks/mattermost-plugin-bigbluebutton#178]
**Hi together,
i try to get the plugin working but with no success. The bbb with Greenlight is working.
The Mattermost log shows the following: Perhaps someone has an idea what i can look for.
THX**

 Sep` 28 16:37:59 team mattermost[323]: {"level":"debug","ts":1632847079.8733804,"caller":"plugin/hclog_adapter.go:54","msg":"\t/Users/harshilsharma/codebase/go/src/github.com/blindsightnetworks/mattermost-plugin-bigbluebutton/vendor/github.com/mattermost/mattermost-server/v5/plugin/client_rpc.go:447 +0x752","plugin_id":"bigbluebutton"}

Sep 28 16:37:59 team mattermost[323]: {"level":"debug","ts":1632847079.873393,"caller":"plugin/hclog_adapter.go:54","msg":"reflect.Value.call(0xc0003ec000, 0xc00000edb8, 0x13, 0x11cb50c, 0x4, 0xc0004a1f18, 0x3, 0x3, 0x0, 0x0, ...)","plugin_id":"bigbluebutton"}
Sep 28 16:37:59 team mattermost[323]: {"level":"error","ts":1632847079.8746939,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"bigbluebutton","error":"unexpected EOF"}
Sep 28 16:37:59 team mattermost[323]: {"level":"debug","ts":1632847079.8747349,"caller":"plugin/hclog_adapter.go:52","msg":"plugin process exited","plugin_id":"bigbluebutton","wrapped_extras":"pathplugins/bigbluebutton/server/plugin.exepid343errorexit status 2"}
Sep 28 16:38:00 team mattermost[323]: {"level":"error","ts":1632847080.3697298,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"bigbluebutton","error":"connection is shut down"}
Sep 28 16:38:00 team mattermost[323]: {"level":"error","ts":1632847080.8568459,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"bigbluebutton","error":"connection is shut down"}
Sep 28 16:38:01 team mattermost[323]: {"level":"debug","ts":1632847081.7892094,"caller":"resend_invitation_email/worker.go:51","msg":"Worker received a new candidate job.","worker":"ResendInvitationEmailJob"}
Sep 28 16:38:02 team mattermost[323]: {"level":"error","ts":1632847082.9156032,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"bigbluebutton","error":"connection is shut down"}
Sep 28 16:38:05 team mattermost[323]: {"level":"error","ts":1632847085.369858,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connection","plugin_id":"bigbluebutton","error":"timeout waiting for accept"}
Sep 28 16:38:05 team mattermost[323]: {"level":"error","ts":1632847085.369899,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, muxBroker couldn't accept connection","plugin_id":"bigbluebutton","serve_http_stream_id":4,"error":"timeout waiting for accept"}
Sep 28 16:38:05 team mattermost[323]: {"level":"error","ts":1632847085.856979,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connection","plugin_id":"bigbluebutton","error":"timeout waiting for accept"}
Sep 28 16:38:05 team mattermost[323]: {"level":"error","ts":1632847085.8570316,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, muxBroker couldn't accept connection","plugin_id":"bigbluebutton","serve_http_stream_id":6,"error":"timeout waiting for accept"}
Sep 28 16:38:06 team mattermost[323]: {"level":"error","ts":1632847086.095917,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"bigbluebutton","error":"connection is shut down"}
Sep 28 16:38:06 team mattermost[323]: {"level":"error","ts":1632847086.223782,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"bigbluebutton","error":"connection is shut down"}
Sep 28 16:38:07 team mattermost[323]: {"level":"error","ts":1632847087.9157255,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connection","plugin_id":"bigbluebutton","error":"timeout waiting for accept"}
Sep 28 16:38:07 team mattermost[323]: {"level":"error","ts":1632847087.9157317,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, muxBroker couldn't accept connection","plugin_id":"bigbluebutton","serve_http_stream_id":8,"error":"timeout waiting for accept"}
Sep 28 16:38:08 team mattermost[323]: {"level":"error","ts":1632847088.2300582,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"bigbluebutton","error":"connection is shut down"}
Sep 28 16:38:09 team mattermost[323]: {"level":"error","ts":1632847089.3173397,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"bigbluebutton","error":"connection is shut down"}
Sep 28 16:38:11 team mattermost[323]: {"level":"error","ts":1632847091.0960553,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connection","plugin_id":"bigbluebutton","error":"timeout waiting for accept"}
Sep 28 16:38:11 team mattermost[323]: {"level":"error","ts":1632847091.0960681,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, muxBroker couldn't accept connection","plugin_id":"bigbluebutton","serve_http_stream_id":10,"error":"timeout waiting for accept"}
Sep 28 16:38:11 team mattermost[323]: {"level":"error","ts":1632847091.2238824,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connection","plugin_id":"bigbluebutton","error":"timeout waiting for accept"}
Sep 28 16:38:11 team mattermost[323]: {"level":"error","ts":1632847091.2239218,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, muxBroker couldn't accept connection","plugin_id":"bigbluebutton","serve_http_stream_id":12,"error":"timeout waiting for accept"}
Sep 28 16:38:12 team mattermost[323]: {"level":"error","ts":1632847092.4957995,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"bigbluebutton","error":"connection is shut down"}
Sep 28 16:38:12 team mattermost[323]: {"level":"error","ts":1632847092.5640016,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"bigbluebutton","error":"connection is shut down"}
Sep 28 16:38:13 team mattermost[323]: {"level":"error","ts":1632847093.2301698,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, muxBroker couldn't accept connection","plugin_id":"bigbluebutton","serve_http_stream_id":14,"error":"timeout waiting for accept"}
Sep 28 16:38:13 team mattermost[323]: {"level":"error","ts":1632847093.2301905,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connection","plugin_id":"bigbluebutton","error":"timeout waiting for accept"}
Sep 28 16:38:14 team mattermost[323]: {"level":"error","ts":1632847094.3174658,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connection","plugin_id":"bigbluebutton","error":"timeout waiting for accept"}
Sep 28 16:38:14 team mattermost[323]: {"level":"error","ts":1632847094.3174682,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, muxBroker couldn't accept connection","plugin_id":"bigbluebutton","serve_http_stream_id":16,"error":"timeout waiting for accept"}
Sep 28 16:38:14 team mattermost[323]: {"level":"debug","ts":1632847094.6661813,"caller":"web/handlers.go:107","msg":"Received HTTP request","method":"POST","url":"/api/v4/channels/members/me/view","request_id":"hhqk848o6pd3zc1d8n8nnjuyxr","host":"team.xxx.com","scheme":"https","status_code":"200"}
Sep 28 16:38:16 team mattermost[323]: {"level":"debug","ts":1632847096.696952,"caller":"web/handlers.go:107","msg":"Received HTTP request","method":"POST","url":"/api/v4/users/status/ids","request_id":"ptorzptbx7frjmjopt8tycx1ao","host":"team.xxx.com","scheme":"https","status_code":"200"}
Sep 28 16:38:16 team mattermost[323]: {"level":"debug","ts":1632847096.7918384,"caller":"resend_invitation_email/worker.go:51","msg":"Worker received a new candidate job.","worker":"ResendInvitationEmailJob"}
Sep 28 16:38:17 team mattermost[323]: {"level":"error","ts":1632847097.495942,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, muxBroker couldn't accept connection","plugin_id":"bigbluebutton","serve_http_stream_id":18,"error":"timeout waiting for accept"}
Sep 28 16:38:17 team mattermost[323]: {"level":"error","ts":1632847097.4959462,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connection","plugin_id":"bigbluebutton","error":"timeout waiting for accept"}
Sep 28 16:38:17 team mattermost[323]: {"level":"error","ts":1632847097.5640924,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, muxBroker couldn't accept connection","plugin_id":"bigbluebutton","serve_http_stream_id":20,"error":"timeout waiting for accept"}
Sep 28 16:38:17 team mattermost[323]: {"level":"error","ts":1632847097.5641053,"caller":"mlog/log.go:251","msg":"Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connection","plugin_id":"bigbluebutton","error":"timeout waiting for accept"}

**Comment by harshilsharma63** [comment]
Hi @cube48AG , are you getting the error on performing a specific oprration?

**Comment by harshilsharma63** [comment]
CLosing this for now. Feel free to re-open if you still face the issue.
