### ISSUE TITLE
I got error when I try to join room externally

### ISSUE THREAD

**Issue by atakancevk** [blindsidenetworks/mattermost-plugin-bigbluebutton#183]
I got error when I try to join room externally
Console:
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0

_Originally posted by @atakancevk in https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/issues/171#issuecomment-939084654_

**Comment by harshilsharma63** [comment]
Hi @atakancevk by any chance was the plugin down at the time? Are you able to reproduce this bug consistently? If yes, can you share the Mattermost server logs when the error occurs?

**Comment by harshilsharma63** [comment]
Closing this as we discussed over email. This was fixed by #192 .
