### ISSUE TITLE
Plugin fails after ending a meeting

### ISSUE THREAD

**Issue by rlKoekie** [blindsidenetworks/mattermost-plugin-bigbluebutton#19]
Hi,

I'm running my own mattermost server (https, with certificates), and my own bigbluebutton server (also https with certificates).
After configuring and enabling the mattermost bigbluebutton plugin I can create a meeting and join it, but as soon as I end the meeting, the plugin stops working.
The mattermost log shows the following:
{"level":"info","ts":1541168870.2771387,"caller":"go-plugin/stream.go:15","msg":"2018/11/02 15:27:50 SUCCESS CREATE MEETINGROOM. MEETING ID: 1CR42FpH5bnF0IpoFu6Blf9pM9L","plugin_id":"bigbluebutton","source":"plugin_stderr"}
{"level":"error","ts":1541168885.3906345,"caller":"plugin/client_rpc.go:322","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"bigbluebutton","error":"unexpected EOF"}
{"level":"error","ts":1541168885.3906338,"caller":"plugin/client_rpc.go:322","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"bigbluebutton","error":"unexpected EOF"}

Whenever I try to start another meeting, I get a message from the bot saying that it failed to create a meeting, and the following error is printed in the log:
{"level":"error","ts":1541168890.8254344,"caller":"plugin/client_rpc.go:322","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"bigbluebutton","error":"connection is shut down"}

Is there a way to debug this easily? (Or did I do something wrong somewhere?)

Thanks in advance for your time,
Hans

**Comment by rlKoekie** [comment]
I forgot to add some details:
Mattermost server version 5.4.0
BigBlueButton server version 2.0.0-13
Plugin version 2.0 (also tested 2.0.1)

bbb-conf --version output:
```
ii  bbb-apps                              1:2.0.0-52                                 amd64        BigBlueButton applications for Red5
ii  bbb-apps-akka                         2.0.0-151                                  all          BigBlueButton Apps (Akka)
ii  bbb-apps-screenshare                  1:2.0.0-41                                 amd64        BigBlueButton screenshare module for Red5
ii  bbb-apps-sip                          1:2.0.0-15                                 amd64        BigBlueButton SIP module for Red5
ii  bbb-apps-video                        1:2.0.0-29                                 amd64        BigBlueButton video module for Red5
ii  bbb-apps-video-broadcast              1:2.0.0-8                                  amd64        BigBlueButton video broadcast module for Red5
ii  bbb-client                            1:2.0.0-394                                amd64        BigBlueButton Flash client
ii  bbb-config                            1:2.0.0-80                                 amd64        BigBlueButton configuration utilities
ii  bbb-freeswitch-core                   2:2.0.0-48                                 amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                 1:1.6.7-9                                  amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                        2.0.0-27                                   all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                             1:2.0.0-475                                amd64        The HTML5 components for BigBlueButton
ii  bbb-mkclean                           1:0.8.7-4                                  amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation             1:2.0.0-28                                 amd64        BigBluebutton playback of presentation
ii  bbb-record-core                       1:2.0.0-33                                 amd64        BigBlueButton record and playback
ii  bbb-red5                              1:1.0.8-40                                 amd64        The Red5 server for BigBlueButton
ii  bbb-swftools                          1:0.9.2-2                                  amd64        The swftools files for BigBlueButton
ii  bbb-transcode-akka                    2.0.0-6                                    all          BigBlueButton Transcoder
ii  bbb-web                               1:2.0.0-93                                 amd64        BigBlueButton API
ii  bbb-webrtc-sfu                        1:2.0.0-76                                 amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                         1:2.0.0-13                                 amd64        Open source web conferencing platform (bbb)
```

**Comment by viktorjamrich** [comment]
Have exactly the same issue...

@rlKoekie have you managed to resolve this?

Thanks a lot mate ;)

**Comment by rlKoekie** [comment]
Unfortunately not, I switched to use jitsi instead. This of course has a lot less features, but the video calls work well.

**Comment by ffdixon** [comment]
Hi @viktorjamrich or @rlKoekie, we're looking for some help from a developer in the Mattermost community to resolve this issue.  Do either of you have experience with developing Mattermost plugins?

**Comment by rlKoekie** [comment]
Nope, sorry.
 I did look into the source code a little bit to see if I could figure the problem. The conclusion was that it takes more than 15 minutes to properly understand what is going on :-)

**Comment by ffdixon** [comment]
Well, yes that's true :-).  

Still, thanks for checking out BigBlueButton.  Our engineering focus has been recently on BigBlueButton HTML5.   We're not sure why the plugin stopped working (it looked good when we first released it).  We'll keep working with the Mattermost community to resolve the issue.

**Comment by harshilsharma63** [comment]
@rlKoekie do you still face this issue? I cannot seem to reproduce it.

**Comment by rlKoekie** [comment]
I have not tried to run the BBB plugin in our mattermost instance lately. Feel free to close this issue if it cannot be reproduced.

**Comment by mightyx1** [comment]
Hi Guys i am still facing the same issue with the latest Containers. has anyone found a solution? id bbb working on mattermost ?

**Comment by IulianDita** [comment]
Hey there people. I am having the same issue.

bbb server (AWS EC2)
BigBlueButton Server 2.2.3 (1833)
Kernel version: 4.4.0-1104-aws
Distribution: Ubuntu 16.04.6 LTS (64-bit)
Memory: 4044 MB
CPU cores: 2

Mattermost is running on Gitlab Omnibus version 12.9.1, and BBB plugin is version 2.1.0, running on Debian Buster (on premise).

**Comment by muriloht** [comment]
I have the same problem here...

**Comment by IulianDita** [comment]
I enabled debug, here's a sample of what's going on. Any ideas?
```
2020-04-22_12:45:32.13569 {"level":"debug","ts":1587559532.1355817,"caller":"plugin/hclog_adapter.go:35","msg":"panic: runtime error: slice bounds out of range [:-1]","plugin_id":"bigbluebutton"}
2020-04-22_12:45:32.13707 {"level":"error","ts":1587559532.136928,"caller":"mlog/log.go:175","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"bigbluebutton","error":"unexpected EOF"}
2020-04-22_12:45:32.13716 {"level":"debug","ts":1587559532.1370885,"caller":"plugin/hclog_adapter.go:33","msg":"plugin process exited","plugin_id":"bigbluebutton","wrapped_extras":"path/var/opt/gitlab/mattermost/plugins/bigbluebutton/server/plugin.exepid121168errorexit status 2"}
2020-04-22_12:45:38.71017 {"level":"debug","ts":1587559538.7098536,"caller":"plugin/supervisor.go:121","msg":"Error pinging plugin","error":"connection is shut down"}
2020-04-22_12:45:38.71018 {"level":"error","ts":1587559538.7099595,"caller":"plugin/health_check.go:90","msg":"Health check failed for plugin","id":"bigbluebutton","error":"Plugin RPC connection is not responding"}
2020-04-22_12:45:38.71019 {"level":"error","ts":1587559538.71,"caller":"mlog/log.go:175","msg":"RPC call OnDeactivate to plugin failed.","plugin_id":"bigbluebutton","error":"connection is shut down"}
2020-04-22_12:45:38.71019 {"level":"warn","ts":1587559538.7100275,"caller":"plugin/hclog_adapter.go:51","msg":"error closing client during Kill","plugin_id":"bigbluebutton","wrapped_extras":"errconnection is shut down"}
```

**Comment by harshilsharma63** [comment]
This should be fixed in the latest release. Closing this one for now. Feel free to reopen if you still face it in the latest release.
