### ISSUE TITLE
Too verbose info level logging

### ISSUE THREAD

**Issue by vmakarenko** [blindsidenetworks/mattermost-plugin-bigbluebutton#191]
The `mattermost.log` is overflooded by messages like this:
```log
{"level":"info","ts":1636588802.859413,"caller":"mlog/sugar.go:21","msg":"Successfully got recordings info","plugin_id":"bigbluebutton"}
```
Eg, `mattermost.log` has 201902 lines, **200921** of them are `"Successfully got recordings info"` messages.
System Console->Logging->File Log Level: "INFO"

**Comment by harshilsharma63** [comment]
Agreed, it shouldn't be that verbose.
