### ISSUE TITLE
Create Meeting Failure

### ISSUE THREAD

**Issue by harshilsharma63** [blindsidenetworks/mattermost-plugin-bigbluebutton#195]
Creating an issue on behalf of @mppg99

Original content -

> Same issue with us. we tried several URL configurations with /api tailing and without. Even the demo URL (http://test-install.blindsidenetworks.com/bigbluebutton/api) isn't working...
> Mattermost 5.39.0
> bigbluebutton plugin 4.2.0
> _Originally posted by @mppg99 in https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/issues/190#issuecomment-976377586_

**Comment by harshilsharma63** [comment]
@mppg99 what error do you get? Can you verify your Mattermost SiteURL?

**Comment by mppg99** [comment]
@harshilsharma63 Live-URL test in Mattermost is working.

Error in Browser:
`/api/v4/posts/an856bk51ins3m6psy8oynw7te/actions/bigBlueButtonJoinMeeting:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
fetch_etag.ts:39 POST https://.../api/v4/posts/an856bk51ins3m6psy8oynw7te/actions/bigBlueButtonJoinMeeting 400 (Bad Request)
u @ fetch_etag.ts:39
(anonymous) @ client4.ts:3781
(anonymous) @ client4.ts:3775
(anonymous) @ client4.ts:2152
(anonymous) @ posts.ts:1188
(anonymous) @ index.js:8
(anonymous) @ redux.js:546
(anonymous) @ message_attachment.tsx:190
onClick @ action_button.tsx:61
s @ react-dom.production.min.js:14
m @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
p @ react-dom.production.min.js:15
ot @ react-dom.production.min.js:52
at @ react-dom.production.min.js:51
it @ react-dom.production.min.js:52
ht @ react-dom.production.min.js:56
q @ react-dom.production.min.js:287
U @ react-dom.production.min.js:19
$t @ react-dom.production.min.js:70
Xt @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
Gn @ react-dom.production.min.js:122
R @ react-dom.production.min.js:287
Vt @ react-dom.production.min.js:68`

Error on Server
`Nov 30 09:31:23 ... mattermost: {"level":"error","ts":1638261083.3844247,"caller":"mlog/sugar.go:25","msg":"Error occurred in creating meeting when joining. Error: XML syntax error on line 78: element <link> closed by </head>","plugin_id":"bigbluebutton"}`
And
`Nov 30 09:31:23 ... mattermost: {"level":"error","ts":1638261083.384659,"caller":"mlog/sugar.go:25","msg":"Error occurred fetching join URL when joining meeting invite","plugin_id":"bigbluebutton","error":"XML syntax error on line 78: element <link> closed by </head>"}`

**Comment by harshilsharma63** [comment]
@mppg99 Looks like the response the plugin is receiving from BBB server is incorrect. I've created a build with additional logs for you to try and get more info from. Please try running the build attached below corresponding to your platform. [These](https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/compare/create-meeting-err-debug?expand=1) are the changes made if you're curious.

Once you run these and try joining a call, please share the logs you see.

If this doesn't work, let's hop on a quick call and see what's going on with your instance. Feel free to send me an email (address in profile).

[bigbluebutton_darwin_amd64.tar.gz](https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/files/7645960/bigbluebutton_darwin_amd64.tar.gz)
[bigbluebutton_windows_amd64.tar.gz](https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/files/7645964/bigbluebutton_windows_amd64.tar.gz)
[bigbluebutton_linux_amd64.tar.gz](https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/files/7645963/bigbluebutton_linux_amd64.tar.gz)

**Comment by mppg99** [comment]
sorry for my late reply and thanks a lot for providing the build. because of this, we were able to find the bug. we had a space in the API link, which was due to a space in the scheduling strategy setup in bbb@scale... weird... because of this Mattermost wasn't able to create the room.

Issue can be closed.

**Comment by harshilsharma63** [comment]
@mppg99 I'm glad the issue is resolved for you!

**Comment by thomas-mc-work** [comment]
Maybe it would be good to execute a testing request to the API endpoint once the input field has lost focus. That'll allow the user to receive an immediate feedback. There seem to be the same problems from time to time with some users.
