### ISSUE TITLE
Mattermost hangs entirely when BBB enabled and user enters his own (the "you") channel

### ISSUE THREAD

**Issue by piotr-wegert** [blindsidenetworks/mattermost-plugin-bigbluebutton#20]
Hey folks,

We've been playing with MM and BBB (using your test server) and noticed that MM hangs entirely when BBB plugin is enabled and the user enters his own (the "you") channel. Until the plugin is disabled by the admin the user can't do anything in MM (there is only a white screen).

We've found the following error message that might have something to do with this problem.

![bbb_you_channel_error](https://user-images.githubusercontent.com/45234616/48845139-0a66f200-ed9c-11e8-8c25-ef9400ae6d71.png)

Many thanks
Piotr Wegert

**Comment by ffdixon** [comment]
Got it -- we'll take a closer look.

**Comment by ypgao1** [comment]
Hi, thanks for the report. The issue has been fixed and will be updated in v2.0.2 soon!

**Comment by piotr-wegert** [comment]
Thanks guys for jumping into this!

**Comment by harshilsharma63** [comment]
Closing as already fixed.
