### ISSUE TITLE
Meetings with no recordings polled forever.

### ISSUE THREAD

**Issue by defnull** [blindsidenetworks/mattermost-plugin-bigbluebutton#204]
It looks like meetings that are polled for recordings but to not have any, are never removed from the recording waiting list and polled forever.

https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/blob/d65cd7f68d157f031eeee59dbbdbb5d593956f35/server/responsehandlers.go#L96-L101

Meetings are only removed from the waiting list if `Meeting.LoopCount > 144` or if there are recordings for that meeting. I could not find any code that increments `Meeting.LoopCount`, so for meetings with no recordings, the poller will never give up. This results in a growling list of meetings that are polled every 2 minutes.

**Comment by harshilsharma63** [comment]
Oh damn! That's a bug oversight on my part. This will be fixed ASAP. Thanks for reporting this 👍
