### ISSUE TITLE
UX: Join meeting

### ISSUE THREAD

**Issue by thomas-mc-work** [blindsidenetworks/mattermost-plugin-bigbluebutton#208]
## Situation

When a user wants to join a meeting two click are required:

![image](https://user-images.githubusercontent.com/6542498/152788152-e21e5fa2-6549-4fcc-83d1-4443ead9a965.png)

Clicking the first marker leads to the second one being shown. Then the containing link ("here") has to be clicked.

Wouldn't it be possible to join directly by clicking the "Join Meeting" button? Maybe having a look at [the Jitsi Meet Plugin for Mattermost](https://github.com/mattermost/mattermost-plugin-jitsi) might help to get an idea about the implementation.

**Comment by harshilsharma63** [comment]
Thanks for the suggestion @thomas-mc-work. I'm taking a look.

**Comment by thomas-mc-work** [comment]
Would you accept donations to accelerate certain issues?

**Comment by harshilsharma63** [comment]
Hi @thomas-mc-work ! I'm glad you considered this project for donations :) but it's not really needed.

This is a bit tricky to implement without causing other annoying issues. I have just one part of the implementation to figure out. Expect this to be done and released in about 2 weeks from now.

**Comment by harshilsharma63** [comment]
Hi @thomas-mc-work The feature has been implemented for v4.4. I have the RC published here - https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/releases/tag/v4.4.0-rc1. Would appreciate if you can give it a try and share any feedback you might have

**Comment by thomas-mc-work** [comment]
I'll test it immediately.

**Comment by thomas-mc-work** [comment]
It works perfectly, thank you!

**Comment by harshilsharma63** [comment]
Thanks for checkout it out @thomas-mc-work !
