### ISSUE TITLE
Direct meeting invite modal 'Join Meeting' button doesn't open correct url

### ISSUE THREAD

**Issue by nerboda** [blindsidenetworks/mattermost-plugin-bigbluebutton#21]
When starting a meeting directly with another user, the 'Join Meeting' button in the modal doesn't open the correct meeting url. This is because, in [root.jsx](https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/blob/master/webapp/components/root/root.jsx#L118), the `getJoinURL` method passes the wrong arguments to `actions.getJoinURL`. It looks like the `channelId` and `meetingId` data are actually held in the state, rather than being passed as props. Basically, it looks like the code was just copied over from [post_type_bbb.jsx](https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/blob/master/webapp/components/post_type_bbb/post_type_bbb.jsx#L100), which, being a child component, does in fact have that data passed as props.

The fix looks straightforward so I'm gonna work on it and make a pr. Please weigh in if you know something I don't.

**Comment by ffdixon** [comment]
We would welcome a pull request.

**Comment by ypgao1** [comment]
Hi thanks for finding the issue. You're insights were correct and the issue has now been fixed. v2.0.2 should reflect this change.

**Comment by nerboda** [comment]
@ypgao1 awesome! Closing this out.
