### ISSUE TITLE
"End Meeting" only for the creator

### ISSUE THREAD

**Issue by thomas-mc-work** [blindsidenetworks/mattermost-plugin-bigbluebutton#214]
**Describe the bug**

Maybe not exactly a bug, but rather a confusion. User A creates a meeting. User B sees the entry in the chat, including the button that says "End Meeting". When User B clicks on it, then he receives this message:

> You cannot end this meeting. Only the meeting creator can end the meeting.

**To Reproduce**

1. User A creates a meeting
2. User B sees the entry in the chat, including the button that says "End Meeting"
3. User B clicks on it, then he receives that message

**Expected behavior**

All other user except User A shouldn't see the "End Meeting" button.

**Environment:**

 - Mattermost version: 6.4.1
 - Plugin version: 4.3.1

**Comment by harshilsharma63** [comment]
HI @thomas-mc-work ! That's a valid point but unfortunately, the plugin system doesn't allow those buttons to be displayed or hidden conditionally.
