### ISSUE TITLE
window mattermost

### ISSUE THREAD

**Issue by AleksandrMikoshi** [blindsidenetworks/mattermost-plugin-bigbluebutton#220]
Hello.
I would like to ask a question:

When calling in MM, in the invitation to the call - a link and a button.
When you click on the button, it transfers to the browser to the call, and when you click on the link, an additional MM window opens with a meeting.
Is it possible to do something when you click on the button, an additional window opens, and in this case the link can be removed.

**Screenshots**
<img width="353" alt="Screenshot 2022-06-15 at 5 16 13 PM" src="https://user-images.githubusercontent.com/79300692/173852059-f9a75d86-13ed-4326-9fd6-786a5d986a29.png">
<img width="844" alt="Screenshot 2022-06-15 at 5 26 47 PM" src="https://user-images.githubusercontent.com/79300692/173852070-565428d3-46d0-4bbc-be9a-6f2425d30452.png">

**Environment:**
 - Mattermost version: 6.7.0
 - Plugin version 4.4.0

**Comment by harshilsharma63** [comment]
HI @AleksandrMikoshi !

The purpose of having the link there is so you can copy it and share it with someone outside your Mattermost organization. For example, if you wanna have a BBB call with a client, you can share this URL with them.

The `Join Meeting` button is for a logged-in user to connect to the call. They are not the same.

There is a plugin setting in the Mattermost System console to disable generating the Share URL if you need to.

> Is it possible to do something when you click on the button, an additional window opens, and in this case, the link can be removed.

It is possible but having an audio-video call run in a browser would be more stable as BBB is tested on web browsers but ot the Mattermost desktop app wrapper.

Hope this helps.
