### ISSUE TITLE
scalelite balancer

### ISSUE THREAD

**Issue by AleksandrMikoshi** [blindsidenetworks/mattermost-plugin-bigbluebutton#224]
**Describe the bug**
Hello.
Faced the following issue:
We have three BBB servers deployed, in front of them is the scalelite balancer and greenlight itself.
Only one BBB server can be specified in the plugin, but there is no balancer itself. In this vein, all load balancing functions are lost. all MM calls will go through one BBB server.

Is there a solution to this issue or plans for implementation?

**Environment:**
 - Mattermost version: 7.1.2
 - Plugin version 4.4.0

**Comment by harshilsharma63** [comment]
@AleksandrMikoshi you can use the URL of your scalite server. Dis it work if you do that?

**Comment by AleksandrMikoshi** [comment]
Hello. Sorry for not answering for a long time.
Yes, I use URL and secret key for scalelite and it is work.
Thanks

**Comment by harshilsharma63** [comment]
Awesome! I'm glad it worked for you!
