### ISSUE TITLE
from_webhook is wrong type

### ISSUE THREAD

**Issue by jasom** [blindsidenetworks/mattermost-plugin-bigbluebutton#225]
[here](https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/blob/0062a2d09185e8e5aa1020e67ea6ff64c312dda9/server/helpers.go#L225) from_webhook is set to `true` but per the mattermost V4 api `from_webhook` is of type String, so it should actually be set to `"true"`.  Yes this is stupid, but clients that parse the messages strictly (e.g. matterhorn, or anything else that uses the haskell mattermost api implementation), will throw an error when encountering the malformed message.

**Comment by harshilsharma63** [comment]
Thanks for posting this @jasom . I'll update it.
