### ISSUE TITLE
Meeting abruptly ends when changing channels in mattermost

### ISSUE THREAD

**Issue by cbrand-ludlums** [blindsidenetworks/mattermost-plugin-bigbluebutton#24]
Hi, I'm testing out the bigbluebutton plugin for mattermost teams server v5.5.  Using the current release plugin, v2.0.1. After starting a meeting, if that user switches to a different channel in mattermost, the meeting ends for everyone.  Is this intended or normal?  Also, I'm using the big blue button default test server and so far, I've not been able to view any saved recordings.

**Comment by ffdixon** [comment]
Thanks for reporting this (it sounds like a bug).  We'll take a closer look.

> Also, I'm using the big blue button default test server and so far, I've not been able to view any saved recordings.

That server gets a lot of use, so your recordings may take a few hours to process.  With the extra users coming in from MatterMost we're looking at upgrading the server.  Alternatively, if you have a spare server, you can setup your own BigBlueButton server (we have an install script that can install and configure the server with a single command).  See https://github.com/bigbluebutton/bbb-install

**Comment by cbrand-ludlums** [comment]
Hi Fred,

We did some testing and so far, if anyone in the meeting switches to a different channel in mattermost, the meeting ends.  If you need any help troubleshooting this, I can help if needed.

On the test server issue, I was thinking that might be the case.  I can bring up a server to host the BigBlueButton server for testing.

**Comment by ypgao1** [comment]
Hi, thanks for identifying the bug with meetings ending when channels switch. Issue seems to be fixed and will be updated in v2.0.2.

Recordings seems to be saved on other servers but not with test-install due to heavy traffic. This is currently being investigated but I recommend trying out the recording feature on your own server. Let us know how it goes!

**Comment by cbrand-ludlums** [comment]
Hi, you've fixed the issue.  The meeting continue perfectly after changing channels in mattermost.  I'm in the process of setting up our own server to test with.  Thanks!
