### ISSUE TITLE
Missing video option when chat started

### ISSUE THREAD

**Issue by tsaruks** [blindsidenetworks/mattermost-plugin-bigbluebutton#26]
Hi,
after installed BigBlueButton v.5.2 in any our laptops missing video button in the meeting screen.
However, sound work fine.
Please, help fix this issue.

Thanks,
Sergiy

**Comment by harshilsharma63** [comment]
HI @tsaruks . Do you still face this issue or is it resolved?

**Comment by harshilsharma63** [comment]
Closing as stale. Feel free to reopen if you still face it in the latest release.
