### ISSUE TITLE
"Join meeting" button doesn't start the meeting

### ISSUE THREAD

**Issue by gdelachat** [blindsidenetworks/mattermost-plugin-bigbluebutton#27]
Hello,

I have installed a BBB server using bbb-install.sh script, everythings is ok on this side, I'm able to login ton greenlight and starting conference.

So I have installed 2.0.2 mattermost plugin from release package. On the plugin configuration, I have setup API URL & Secret, but when I try to join a meeting, I have a new tab opening in my browser with the URL "https://blindsidenetworks.com/" and nothing more.

I tested with test-install parameter, it works, when the new tab is opening, after showing "https://blindsidenetworks.com/" I have a redirect to your test instance.

Thanks for you help.

Regards,
Guillaume

**Comment by ffdixon** [comment]
When you configure the Mattermost plugin, did you enter the URL in the form

~~~
  https://<server>/bigbluebutton/api
~~~

**Comment by gdelachat** [comment]
Hello,

Yes I did it

Regards,
Guillaume

**Comment by jasonblais** [comment]
Hey @gdelachat - did you try if it works with the default options provided in the System Console > Plugins > BigBlueButton settings page?

This helps us narrow down the potential problem.

**Comment by gdelachat** [comment]
Hello,

@jasonblais, like i said on the 1st thread, if I use default settings, it works, meeting is opening on the test instance (from blindsidenetworkds).

Regards,
Guillaume

**Comment by jasonblais** [comment]
Thanks @gdelachat! Wasn't sure if the test-install parameter were referring to that.

@ffdixon Wondering if you'd know potential causes of the error reported above?

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<response>
<returncode>SUCCESS</returncode>
<version>2.0</version>
</response>
```

**Comment by eyebank** [comment]
Dear All:
I am having the same exact issue. 
Joining a meeting in Mattermost displays the same message as above:

"This XML file does not appear to have any style information associated with it. The document tree is shown below.
<response>
<returncode>SUCCESS</returncode>
<version>2.0</version>
</response>"

I did notice in the following video: https://www.youtube.com/watch?v=gg7J9B4wGa4

The url is html5client when launched in thier mattermost demo. Any correlation?

Thanks

**Comment by ffdixon** [comment]
It might be an update that occurred in mattermost as this was working before (when we took the video).

@eyebank  How fluent are you in development of mattermost plugins (or do you know anyone who could potentially help out)?

**Comment by cseeger-epages** [comment]
any hint here we have the same problem on our mattermost/bbb instance

**Comment by cseeger-epages** [comment]
we did test some stuff and recognized that using chrome 75.0.3770.80 everything works as intended on our live and test system. 

But when using other clients like Rambox/Wavebox we only get the redirect link hardcorded in https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/blob/93b897ab2bf5233ed5809da58ee211aad946712a/webapp/components/root/root.jsx#L117 used for generating the /plugins/bigbluebutton/webapp/bigbluebutton_bundle.js

here within Wavebox the correct join url comes back from the api but is not used as the link for the `Join Meeting` button. It looks like this is done via js on runtime and seems not to work on these clients properly thats why the default link is used.

**Comment by eyebank** [comment]
resolved.

**Comment by cseeger-epages** [comment]
:+1:

**Comment by driehle** [comment]
@cseeger-epages The reason is that Rambox (and probably Wavebox as well) uses a User Agent withouth the "Electron/" keyword inside the service web views. I solved this by adding the following custom code the the service configuration when using Rambox:

```javascript
(function() {
    var userAgent = navigator.userAgent.toString();
    Object.defineProperty(navigator, 'userAgent', {
        get: function () { return userAgent + ' Electron/'; }
    });
})();
```

This overrides the user agent inside the Mattermost web view and makes the "Join meeting" button functional when using Rambox. If Wavebox has a similar setting for injecting custom code, that should work for Wavebox as well.
