### ISSUE TITLE
share the screen

### ISSUE THREAD

**Issue by suicidesky92** [blindsidenetworks/mattermost-plugin-bigbluebutton#28]
Is it possible to share the screen?

**Comment by ffdixon** [comment]
Yes, we put together a video of how the interaction of BigBlueButton works with Matterhorn (including the desktop sharing), see

  https://www.youtube.com/watch?v=gg7J9B4wGa4

**Comment by benberlin7** [comment]
@ffdixon  When I create a room via MM there is no option to share the screen. (I cannot become presentator as well)
steps
- I clicked on BBB button in MM. 
- a link pops up
- I open this link in my browser
- I'm entering the room (as "guest", even when I'm logged in in another tab I have to enter a name)

![grafik](https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/assets/47561019/67cdf8f2-5d17-448d-b0bf-df9cc484e814)

- When I create a room on the BBB frontend via greenlight I have no problems and can share screen / become presentator (even as guest)
- Admin panel room settings :
```
Allow Room to be recorded false
Require users to be signed in before joining opt,default-disable
Require moderator approval before joining opt,default-disable
Allow any user to start a meeting opt-default-enable
Gives all users the moderator privileges in BigBlueButton when they join the meeting force true
Mute users when they join opt default-disabled
Viewer Access Code opt default-disabled
Moderator Access Code opt default-disabled
```

- BBB-MM Plugin settings :
```
Only admins become mods : false
Process recs : false
Allow recs : false
allow external users to join meertings : true
```

 -BBB is hosted via Ubuntu Server v20.04, 
- BBB v2.7
- Greeenlight v3
- MM BBB Plugin 4.5.0 (version is shown as 4.4 , known bug)
- MM Enterprise Edition Free,  v5.5.1

What am I doing wrong?
