### ISSUE TITLE
Allow External URL option for generated meetings

### ISSUE THREAD

**Issue by S1M0N** [blindsidenetworks/mattermost-plugin-bigbluebutton#29]
Hello, 

Currently there appears to be no way to invite or allow an external user to join a meeting generated using this plugin in Mattermost. Would it be possible to add a functionality to support this? This would be useful in situations where an external user may be needed in a meeting (such as a business partner or external support member) but they don't have access to MM, or if they do, but don't have access to the channel where the meeting was started. 

Thanks, 
Simon

**Comment by cadavre** [comment]
I'm facing the same problem now while initializing Mattermost and BBB on new communication platform for our company.

One of biggest pains is that once Meeting is created – anyone but channel-users can't join. We need to invite external customers (best – via pretty URL like from Greenlight) that doesn't have a MM accounts.

Another, but very similar case is – inviting some to extend 1:1 meeting. That would be partially possible if above's link would be available.

**Comment by ffdixon** [comment]
Thanks for the feedback!

With an invite URL, we would need to bring the user to an intermediate page that asks them for their name (as they are external to Mattermost) and then bring them into the meeting.

We'll give some thought about the best way to do this and update this issue when we have progress.

**Comment by wepe53** [comment]
Has this issue been solved in between?
We have the same problem to invite external (non MM) users to a videoconference - how to do this?
Thanks!

**Comment by harshilsharma63** [comment]
I'll check this out.

**Comment by harshilsharma63** [comment]
The ability to invite an external user to the meeting is already added. Closing this one.
