### ISSUE TITLE
Mattermost client crash with emoji username

### ISSUE THREAD

**Issue by xvilo** [blindsidenetworks/mattermost-plugin-bigbluebutton#30]
When a username in Mattermost has an emoji in it (yes this is possible), you can 'crash' the client. 
Steps to reproduce:

1. Setup a username with emoji
2. Go to a user or channel
3. Start a BigBlueButton conference

Now both clients crash, if this is done the other way around e.g. TO someone this doesn't happen. Something is 'undefined' and in turn, breaks the react app. 

I do not have any logs at this moment, because I accidentally did this on a live environment and don't want to 'crash' them both again.

**Comment by harshilsharma63** [comment]
@xvilo I tried creating a user with emojies in username but Mattermost doesn't allow them as fasr as I can see. I even checked the Mattermost source code to see what validations does it apply it indeed doesn't allow emojies in username. maybe it did in a version when you reported the bug.

I even tried this with havig emojies in first name, last name, nickname and even position but the plugin works just fine.

Could you please try the same in a more recent version of Mattermost?

**Comment by xvilo** [comment]
I'm sorry, I meant the nickname field. Just added it to our MM client and it worked. However, as far as I can see for now it just works..

**Comment by harshilsharma63** [comment]
@xvilo that's great! Thanks for confirming. Closing the issue now.
