### ISSUE TITLE
Screensharing plugin doesn't work

### ISSUE THREAD

**Issue by 0xSheff** [blindsidenetworks/mattermost-plugin-bigbluebutton#31]
Suggests to install an extension that is already installed in Chrome. Remove and install again doesn't solve the problem

**Comment by ffdixon** [comment]
Which BigBlueButton server are you using to test (did you setup one yourself or are you using a 3rd party)?

**Comment by 0xSheff** [comment]
I have installed my own server (Team edition) and registered the domain in the extension manifest (installed unpacked ext to the chrome).. but screensharing doesn't work

**Comment by ffdixon** [comment]
We'll have a release for BigBlueButton 2.2-beta shortly which, thanks to Chrome 72, will not require a Chrome Extension anymore.

Look for the announcement to the bigbluebutton-dev mailing list (see https://bigbluebutton.org/support).

**Comment by twelch555** [comment]
I spent a couple of hours chasing this issue a couple of weeks back. Make sure you shut down chrome and restart after installing the extension. (I think this was the solution to my issue, although I also tried disabling all extensions and disabling privacy badger which I also run.)

I'm going to guess that you are Mac-based, this seemed to be the platform we were having the issue on. Ironically, the chrome browser running on Windows via Parallels on the same machine had no issues (we tested across multiple browsers and OSs) leading us the conclusion that it was a Mac/Chrome problem. As above, I believe the chrome shutdown/restart enables proper BBB extension functioning.

**Comment by ffdixon** [comment]
We release BigBlueButton 2.2-beta that features a much more capable HTML5 client.  See

 https://groups.google.com/d/msg/bigbluebutton-dev/34SphncjKEw/KJZsbQbEAQAJ

We recommend tryout this version as the HTML5 client no longer needs a chrome extension if your are running Chrome 72 (or later), which was released on Jan 29 and most people are probably running.

You can try it out on our test server at https://test.bigbluebutton.org/.

**Comment by 0xSheff** [comment]
Thank you for your replies!
No, we tested it on a different platforms, Mac and Windows 10, and had these issues. I will try to use 2.2-beta, will see how it work

**Comment by harshilsharma63** [comment]
@0xSheff are you still facing this issue?
