### ISSUE TITLE
Pb url generate on meetings mattermost

### ISSUE THREAD

**Issue by barto95100** [blindsidenetworks/mattermost-plugin-bigbluebutton#34]
I install the plugin but when I click on :" joint Meeting"

I'm redirect to : https://blindsidenetworks.com/

in console seeting the configuration is great with my Secret and url with /bigbluebutton/api

Do you have a idea what's the problem ? 

Thank's

**Comment by gdelachat** [comment]
Same issue as #27

**Comment by harshilsharma63** [comment]
@barto95100 do you still face this issue? I'm able to successfully navigate to meeting from Mattermost.

**Comment by harshilsharma63** [comment]
Please re-open the issue if you still face the problem.
