### ISSUE TITLE
Receive HTLML5CLIENT/joing failed (no such directory)

### ISSUE THREAD

**Issue by sydneysider** [blindsidenetworks/mattermost-plugin-bigbluebutton#35]
I was able to install this beautifully using BBB's instructions on ubuntu 16.04, Mattermost 5.7, and got the BBB MM plugin installed fine. 

The demo worked fine on MM, so I removed the default from my 'sites-enabled' on my BBB server and I keep getting Nginx 404 errors, see error below. This is on an AWS instance, the only complaints I get are about my local IP as opposed to my public ip which is pointing to my dns name, which shouldn't be a problem since I've correct all areas that point to my dns name.

I've created the /html5client/join directories, but then it just keeps throwing FORBIDDEN errors. I've mess with permissions some, but unsure what's correct at this point.

Any help appreciated.

[error] 1398#1398: *98 open() "/var/www/bigbluebutton/html5client/join" failed (2: No such file or directory), client: xxx.xxx.xxx.xxx, server: bigbluebuttonxxxxxxxxxx.com, request: "GET /html5client/join?sessionToken=qhbjfe0eukh4lfsd HTTP/1.1", host: "bigbluebutton.xxxxxxxxxxxx.com"

**Comment by sydneysider** [comment]
When I place the directory /html5client/join, I receive the error - I must be missing something obvious, but not sure. Thanks.

[error] 4036#4036: *9 directory index of "/var/www/bigbluebutton/html5client/join/" is forbidden, client: xxx.xxx.xxx.xxx, server: bigbluebutton.xxxxxxxxxx.com, request: "GET /html5client/join/?sessionToken=sropvcl3nvxya3dq HTTP/1.1", host: "bigbluebutton.xxxxxxxxxx.com"

**Comment by ffdixon** [comment]
Did you install the HTML5 client on your BigBlueButton server?  

To easily setup a BigBlueButton server with HTML5 + SSL (or to upgrade an existing BigBlueButton 2.0 server to have HTML5), check out https://github.com/bigbluebutton/bbb-install

**Comment by sydneysider** [comment]
I ran the bbb-install.sh — isn’t the html5 installer in that script, I see the line there for it. Also, shouldn’t it fail over to the flash version if html5 isn’t present? This part has me a bit confused, especially because in the properties config it’s set to ‘false’ to force clients to html.

**Comment by ffdixon** [comment]
If you want to make the HTML5 client default and not use Flash, you need to make two additional edits, see http://docs.bigbluebutton.org/html/html5-install.html#making-the-html5-client-default.

**Comment by sydneysider** [comment]
Hi, that’s not what I’m trying to do - and J tried that change already anyway and still received the same error. 

I’m just trying to make the product work flash or html5  - doesn’t matter. I ran the install.sh script - the demos worked fine. I installed the mattermost plugin. But it always ends up with the “html5/join” nginx error. Not sure what I’m missing here, if the script is meant to install everything then that /html5/join directory should exist, no? 

Please advise. And your help is much appreciated.

**Comment by sydneysider** [comment]
Hi Fred,

This can be resolved, I started a new instance and ran the install with a -t, and now it works fine. I'm now running into other (known issues) with error 1007. I'll start a new post about this, as this one can be resolved. Cheers.

**Comment by ffdixon** [comment]
Thanks for letting us know.
