### ISSUE TITLE
Release is based off wrong commit

### ISSUE THREAD

**Issue by kgreav** [blindsidenetworks/mattermost-plugin-bigbluebutton#38]
The latest release 2.0.2 (https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/releases/tag/v2.0.2) is based off commit 38513f7c533bdf75a53db07c477a585a529af69f - this is before https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/issues/24 in which  it was noted it would be included in 2.0.2.

Currently you have to build mattermost yourself to get this and a few other bugfixes from back in November. Would we be able to get a new release up to date with the current master?

**Comment by harshilsharma63** [comment]
@kgreav we've released [v2.0.3](https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/releases/tag/v2.0.3) which includes the commit you mentioned above. We suggest you use this release as it includes an extra bug fix as well.
