### ISSUE TITLE
BBB plugin not cooperating with user preview

### ISSUE THREAD

**Issue by piotr-wegert** [blindsidenetworks/mattermost-plugin-bigbluebutton#45]
Hello team, 

I've found two instances where the BBB plugin causes problems when trying to preview a MM user details. It's happening in 5.12 and most likely didn't occur in earlier version as someone would have caught it. When I disable the plugin both issues disappear.

Ok, here are the details:

1) When clicking @username in any channel the whole Mattermost freezes with a white screen. 

![image](https://user-images.githubusercontent.com/45234616/59749340-1e64ca80-927d-11e9-9a2e-9771b0262d4d.png)

I get the following error in the browser console. 

![image](https://user-images.githubusercontent.com/45234616/59749452-4eac6900-927d-11e9-8839-2d591cffcc06.png)

2) Clicking a user avatar doesn't display the user details pop-up. MM doesn't freeze as in problem 1, simply nothing happens. Console logs shows the following error.

![image](https://user-images.githubusercontent.com/45234616/59749504-6b48a100-927d-11e9-832c-35a266fbde5a.png)

**Comment by ffdixon** [comment]
Thanks for sharing this -- we'll update this issue when we have more details on what's causing it.

**Comment by jimscarver** [comment]
Is there any update on this or do we still need to disable BBB in MM?

**Comment by harshilsharma63** [comment]
@piotr-wegert I'm working on resolving this.

**Comment by harshilsharma63** [comment]
@jimscarver @piotr-wegert The fix for this has been released as v2.0.3, available over [here](https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/releases/tag/v2.0.3). I request you to try it out.

**Comment by piotr-wegert** [comment]
@harshilsharma63 works like a charm. Looks like the bug is fixed now, thanks!
