### ISSUE TITLE
Add join meeting link to Mattermost message and in-call chat

### ISSUE THREAD

**Issue by cadavre** [blindsidenetworks/mattermost-plugin-bigbluebutton#57]
Is it possible to show "Join URL" somewhere in UI? Or post the 1st chat message with join link?

We'd like to have a possibility to copy-paste URL to someone from outside the channel.

**Comment by moschlar** [comment]
This would also help with #33

**Comment by Joshndroid** [comment]
Any work being done in this... 6months + later and no real change

**Comment by harshilsharma63** [comment]
@cadavre @moschlar @Joshndroid the join URL is unique per user. The plugin now supports mobile and also allows sharing a sharable URL with external users. This should resolve the issue.
