### ISSUE TITLE
BBB crashing in MM version 5.14.0 and higher

### ISSUE THREAD

**Issue by Sofeltis** [blindsidenetworks/mattermost-plugin-bigbluebutton#58]
Hello,

I have a problem with BBB in version 5.16.0. When I click on someone to popover his information it won't happened anything. Can you please investigate it? I'm attaching a SS also. If you don't know what am I talking about, you can find SS where popover works.
![Image Pasted at 2019-10-21 12-33](https://user-images.githubusercontent.com/6420126/67262860-8daa2f80-f4a6-11e9-9f2b-cc298586b1fb.png)

![Image Pasted at 2019-10-21 19-24](https://user-images.githubusercontent.com/6420126/67262833-723f2480-f4a6-11e9-8e15-554b6c4b1d21.png)

**Comment by harshilsharma63** [comment]
Closing as stale. Feel free to re-open if you face the issue on the latest release.
