### ISSUE TITLE
Error: The meeting ID that you supplied did not match any existing meetings

### ISSUE THREAD

**Issue by Magnusemail** [blindsidenetworks/mattermost-plugin-bigbluebutton#60]
Hello guys,

I have a fresh bbb and mattermost on two servers setup - 

BigBlueButton Server 2.2.0-beta-22 (1477)
Kernel version: 4.4.0-166-generic
Distribution: Ubuntu 16.04.6 LTS (64-bit)

Mattermost Version: 5.16.1
Database Schema Version: 5.16.0
Database: mysql

Local Lan//No FW or iptables 

both work fine when user goes direct to bbb or mattermost (on which have installed the bbb integration with correct details (as tested with api-mate)) however on clicking the video icon button in mattermost it seems that the create command fails to reach bbb from mattermost, and thus the next click on the "join meeting" button opens a new window with the message "Error The meeting ID that you supplied did not match any existing meetings"  

No Firewall or iptables between mattermost and bbb is running in the setup, and on clicking the mattermost video icon nothing is seen in the bbb logs, and thus then when the join meeting button is clicked the error appears, which makes sense if the create command does not leave mattermost.

No SSL issues as servers both work and API tests corectly with the api-mate tool.

Is there any known issue with the create meeting process in the BBB Mattermost plugin for ?

Thanks
Magnus

**Comment by Magnusemail** [comment]
Update - issue was found to use of proxies between servers. Once proxies removed issue resolved.

**Comment by ffdixon** [comment]
Thanks for sharing your solution.  

For the benefit of others, the docs for adding/removing the proxies are here

  https://docs.mattermost.com/install/outbound-proxy.html
