### ISSUE TITLE
Make plugin compatible with Mattermost running in HA mode

### ISSUE THREAD

**Issue by harshilsharma2** [blindsidenetworks/mattermost-plugin-bigbluebutton#61]
One quick thing I found is this-

    p.Meetings = append(p.Meetings[:index], p.Meetings[index+1:]...)

We shouldn't store data in memory and used KV store instead.

**Comment by harshilsharma63** [comment]
Currently we save all meeting data form memory to KV store on plugin deactivation. This will lead to information loss when plugin crases as reported by @hanzei at https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/pull/44#discussion_r295326385 .

**Comment by harshilsharma63** [comment]
This is fixed now. We no longer handle meeting data in memory and use mutex locked access to KV store.
