### ISSUE TITLE
not work then mattermost under location

### ISSUE THREAD

**Issue by agrisvv** [blindsidenetworks/mattermost-plugin-bigbluebutton#71]
Mattermost are under location https://domain.com/mattermost
plugins wants to acccess https://domain.com/plugins/bigbluebutton/create

need to change line:
`````
  this.url = '/plugins/bigbluebutton';

`````
to something like:
````````
 this.getBaseRoute() + '/plugins/bigbluebutton'
`````````

**Comment by harshilsharma63** [comment]
@agrisvv HI, thanks for reporting the issue. This is directly related to https://github.com/mattermost/mattermost-server/issues/14106 and can be fixed with relative ease. Can you confirm that you set the `SiteURL` setting in your Mattermost as `https://<your-domain>/mattermost` ?

**Comment by agrisvv** [comment]
"SiteURL": "https://domain.com/mattermost"
also was try with slash at end - not helped.
now plugin work if i change line from /plugins to /mattermost/plugins in JS

**Comment by grisuthedragon** [comment]
I had the same problem in my setup. I use as well the `mattermost` as subpath. At the moment, I patch the plugin and compile ist myself.:

```
sed -i -e 's#/plugins/bigbluebutton#/mattermost/plugins/bigbluebutton#g' webapp/client/client.js
sed -i -e 's#/plugins/bigbluebutton#/mattermost/plugins/bigbluebutton#g' server/helpers.go
make build
```

But it would be better to read the suburl from the mattermost config.

**Comment by rottaran** [comment]
I have used following javascript code in `webbapp/client/client.js`. It assumes that the mattermost URL always ends in `/TEAMNAME/channels/CHANNELNAME`. I do not know whether this is always the case where this plugin can get activated.

```
this.url = '/' + window.location.pathname.split('/').slice(1,-3).join('/') + '/plugins/bigbluebutton';
```

**Comment by harshilsharma63** [comment]
@agrisvv @rottaran @grisuthedragon  this is fixed in the newer releases. Please upgrade to the latest plugin version. Feel free to re-open this issue if it still doesn't work for you.
