### ISSUE TITLE
Feature request: Attach slides and shared notes to mattermost message

### ISSUE THREAD

**Issue by mhier** [blindsidenetworks/mattermost-plugin-bigbluebutton#74]
The uploaded slides and shared notes should be attached to the mattermost message, even if no recording was made. This would be extremely helpful e.g. for taking meeting minutes in the shared notes.

**Comment by mkuron** [comment]
This feature depends on https://github.com/bigbluebutton/bigbluebutton/pull/8895.

I actually already implemented a quick-and-dirty prototype of your feature request a few weeks ago. It is a PHP script that posts slides, notes and chat logs to the Mattermost channel. It depends on https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/pull/73. I'd be happy to provide that PHP script to anyone interested, but the right way to implement this feature is of course in Go as part of mattermost-plugin-bigbluebutton. I don't know any Go, but I'm happy to help if someone who does know Go wants to take a shot at it.

**Comment by harshilsharma63** [comment]
We've added a link to shared notes in Mattermost. This is how it looks-

<img width="1002" alt="Screenshot 2021-06-16 at 5 19 00 AM" src="https://user-images.githubusercontent.com/18575143/122137487-5dc15400-ce62-11eb-8ab4-75330f210afe.png">

**Comment by harshilsharma63** [comment]
This is resolved by #155
