### ISSUE TITLE
Demo server not working

### ISSUE THREAD

**Issue by uhlhosting** [blindsidenetworks/mattermost-plugin-bigbluebutton#8]
Just installed the plugin in Mattermost 5.1.0 and it went all good. Just that the default server and API provided by it for test are not working.

Nor I have any buttons or options in mattermost for this bigbluebutton webrtc.

Does this conflict with existing webrtc servers?
http://test-install.blindsidenetworks.com/bigbluebutton/api
8cd8ef52e8e101574e400365b55e11a6
https://chat..../

**Comment by jfederico** [comment]
@uhlhosting should we close this issue?

**Comment by uhlhosting** [comment]
@jfederico yes, i have managed to have it work. thank you.
