### ISSUE TITLE
Question: Ending Meetings

### ISSUE THREAD

**Issue by eyebank** [blindsidenetworks/mattermost-plugin-bigbluebutton#80]
Hello: 

I got the plug-in to work well. Not 100% but well enough to consider deploying. I am overjoyed!

On my deployment i noticed that if you end the meeting in BBB, the link in mattermost is still live until someone closes it via "end meeting". 
The issue is that the actual duration of meeting is not accurate.  I can imaging an individual unintentionally leaving a the mattermost meeting link live/open after closing the BBB meeting. I am uncertain how open idle meetings can impact the system.

Question: 
1) Is this a problem with my implementation of MM-BBB?
2) Is there a way the Admin can search for an open meeting and/or automatically close a meeting after an unrealistic time of say 2 hours?

Thanks

**Comment by mkuron** [comment]
There is a configurable timeout to automatically end empty meetings: https://github.com/bigbluebutton/bigbluebutton/blob/41f19a2cd1bc7dae76cbd805cdc3ddfbf1e6ab18/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L179. I have seen the timeout kick in on my install, so I can confirm that it should work. Note that this is not functionality of the MM plugin, but core functionality of BBB itself.

**Comment by eyebank** [comment]
Thank you @mkuron

**Comment by harshilsharma63** [comment]
Closing this as this seems resolved. Feel free to re-open.
