### ISSUE TITLE
Use header BBB icon instead of generic "camera" icon

### ISSUE THREAD

**Issue by cadavre** [blindsidenetworks/mattermost-plugin-bigbluebutton#81]
Hi, some of use are using more that one audio-video communicators. It is hard to distinguish them by looking at the icon fo generic camera.

My suggestion is to create Mattermost-style icon for BBB and use it instead.

<img width="52" alt="Zrzut ekranu 2020-04-16 o 10 04 10" src="https://user-images.githubusercontent.com/461796/79430738-afa1ec00-7fc9-11ea-81a8-8f5afdee6fb8.png">

**Comment by harshilsharma63** [comment]
This makes sense. We can probably add the BBB logo over there.

**Comment by harshilsharma63** [comment]
@cadavre we'll be updating the icon to look like this one-

<img width="544" alt="Screenshot 2021-06-09 at 5 07 47 AM" src="https://user-images.githubusercontent.com/18575143/121271135-a5833100-c8e0-11eb-896c-b646757afe58.png">

**Comment by danielberndt** [comment]
This change adds an extra barrier for non-tech savvy users (who only have one video integration available).

These folks likely aren't aware of big blue buttons branding and won't be able to recognise that the "b" icon leads them to a video call.

Is it worth opening an issue for this to ask for a settings option?
