### ISSUE TITLE
Enhancement: Add Option to Disable "View Recordings" Button

### ISSUE THREAD

**Issue by fkellner** [blindsidenetworks/mattermost-plugin-bigbluebutton#82]
Since BigBlueButton often is used in a corporate context, compliance with data protection laws and concerns is important. One such concern is that worker representation **may not be okay with using a video conferencing tool with the option to record meetings.**
Now, I am really thankful for this Plug-In which is of great help to establish self-hosted Mattermost as a real alternative to data-hungry Cloud solutions, and I am not deeply familiar with the technological architecture of BBB, but...

I read somewhere that you can deactivate the possibility to record a meeting when you create it through the API. If that really is the case, it would be great if you could add a setting to **deactivate/activate the recording capabilities for meetings created by the Plug-In.**

**Comment by mkuron** [comment]
That option is currently set to true globally: https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/blob/8d7cb82407753b1ea354a7607d7d4ae6b63c4c17/server/helpers.go#L55. If you want to disable recording globally, you can already do that for the entire BBB server (i.e. not specific to the MM plugin).

```bash
sudo sed -i 's/allowStartStopRecording=./allowStartStopRecording=false/g' \
  /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
sudo sed -i 's/disableRecordingDefault=./disableRecordingDefault=true/g' \
  /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
```

**Comment by fkellner** [comment]
Thank you for the quick reply and support! I guess that solves my problem.

However, it would probably be a nice-to-have if the "View Recordings"-Option in the Button Modal could be turned off, too, so should I leave this open as inspiration in case somebody has the time to bother with this detail, or close it?

**Comment by mkuron** [comment]
Yes, I'd like to see that too. Perhaps you can change the issue title to _Disable "View Recordings" button_ or something.

**Comment by eyebank** [comment]
I posted a similar request  here:

[https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/issues/79](url) 

Thanks

**Comment by moschlar** [comment]
For the time being, you can now (as of https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/releases/tag/v3.2.0) disable processing recordings in the plugin, so the recordings won't show up.

That's not sufficient though, especially from a data protection perspective.

**Comment by harshilsharma63** [comment]
This should be easy to implement. I'll try this out.

**Comment by harshilsharma63** [comment]
This has been implemented and will be released at the end of this week or the start of next week.

I've added a plugin config to allow or disallow the meeting recording option, as pointed out by @mkuron (thanks!).


**The plugin config-**
<img width="858" alt="Screenshot 2021-07-27 at 6 26 21 AM" src="https://user-images.githubusercontent.com/18575143/127078036-346e09cd-d175-4066-950d-5de183106a3d.png">


**BigBlueButton when recording is disabled-**
<img width="265" alt="Screenshot 2021-07-27 at 6 26 58 AM" src="https://user-images.githubusercontent.com/18575143/127078101-6015c28a-fe18-41ab-a923-77c1021aba46.png">

**Comment by harshilsharma63** [comment]
> Yes, I'd like to see that too. Perhaps you can change the issue title to _Disable "View Recordings" button_ or something.

Disabling the view recording button won't make any difference. The way that button works is by triggering a Mattermost search for `#recording` in messages. A user can themselves make the same search without the button.
