### ISSUE TITLE
Sync BigBlueButton chat with Mattermost channel

### ISSUE THREAD

**Issue by flowy2020** [blindsidenetworks/mattermost-plugin-bigbluebutton#84]
Hi,
i already have searched on google, but didn't find anything.
We are using BBB as integration with MM.
We set up a MEETING channel, which is dedicated to meetings, so people won't have to search around where a daily meeting join button is, since we have a lot of chatting in multiple channels going.
Since MM generated BBB meetings are somewhat volatile and people aren't used to check the chat in the meeting, is there any way to sync the BBB chat with the MM channel chat, so people will actually see new messages?
Thank you in advance.
Regards,
Florian

**Comment by harshilsharma63** [comment]
@flowy2020 syncing chat is out of scope of this plugin but we are adding a link in Mattermost to BBB Public Notes. Here's a sneak peak-

<img width="805" alt="Screenshot 2021-05-31 at 4 34 43 PM" src="https://user-images.githubusercontent.com/18575143/120184020-1d40c400-c22e-11eb-8794-d255961642b8.png">

**Comment by harshilsharma63** [comment]
This has been added in v3.1.0.
