### ISSUE TITLE
Clicking "Join meeting" sometimes opens blindsidenetworks website

### ISSUE THREAD

**Issue by zorun** [blindsidenetworks/mattermost-plugin-bigbluebutton#85]
When clicking "Join meeting" in the mattermost webapp, sometimes it opens https://blindsidenetworks.com in a new tab instead of the expected meeting.

With Firefox on Linux, this happened from time to time (not always). A friend on Windows told me it happened every time. I don't know which browser it was, but it was not Firefox. With Firefox it was working as expected.

Looking at the code, the goal seems to be to workaround pop-up blocking in browsers: https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/blob/master/webapp/components/root/root.jsx#L116
However, this code looks prone to race conditions. Could it work with `about:blank` instead of an actual URL? Isn't there a cleaner solution?

**Comment by eyebank** [comment]
+100 for you sir @zorun . This has plauged me for several months! I thought the plug in was broken, meetings would not launch within chrome - was usining chrome browser exclusively. The only instance the plug-in would work on chrome browser is when you use the --clean command and it would only work once. 
Finally, just this week i switched to Firefox browser and "Join Meeting" button worked Every. Single. Time. We had to mandate all users use firefox. 

I could not believe i wasted months testing and complaining on this forum and others. If you found a potential cause, i hope they figure it out.

**Comment by louisroyer** [comment]
This happens to me every time on firefox when I activate temporary containers addon.

**Comment by iddelacruz** [comment]
Disable and enable plugin fix this problem.
