### ISSUE TITLE
BBB moderator for "team_admin".

### ISSUE THREAD

**Issue by shurakov-igor** [blindsidenetworks/mattermost-plugin-bigbluebutton#92]
Is it possible to add a setting to limit the rights to create a webinar only for "team_admin" with the rights of a moderator of a webinar? The rest of the team members are like ordinary listeners, without the possibility of intercepting the rights of a moderator. As I understand it, the BBB API allows this, but MM did not understand ..

**Comment by harshilsharma63** [comment]
This will be released as part of v2.2.
