### ISSUE TITLE
How can I change the URL after ending a BBB meeting?

### ISSUE THREAD

**Issue by n3niu** [blindsidenetworks/mattermost-plugin-bigbluebutton#93]
After ending a BBB meeting initiated from the Mattermost client the browser opens https://<SiteURL>/plugins/bigbluebutton/redirect showing a blank page.
If possible how can I redirect to another URL?
Thank you

**Comment by harshilsharma63** [comment]
@n3niu can you verify that you have `SiteURL` configured in your Mattermost installation?

**Comment by harshilsharma63** [comment]
@n3niu also, how are you opening the meeting from Mattermost after ending it?

**Comment by n3niu** [comment]
Hi and a big fat sorry for coming back that late. I just moved away from BBB and so there's no more problem. Anyway, I highly appreciate your response. Thank you very much.
