### ISSUE TITLE
bbb plugin flashy incoming "call"

### ISSUE THREAD

**Issue by paulrolandw** [blindsidenetworks/mattermost-plugin-bigbluebutton#95]
Hello we are evaluating bbb on mattermost and willing to go full prod.
the only complaint we have from inside is that when somebody "calls" in it's easy to miss it because it's not popping up or making any sound rather than the default msg one to join the meeting.
Is there anything we can do on that? our goal is to replace skype completely.

**Comment by harshilsharma63** [comment]
@paulrolandw the issue is now resolved. Please try out the latest version of the plugin.
