### ISSUE TITLE
Republish Videos?

### ISSUE THREAD

**Issue by greatfireball** [blindsidenetworks/mattermost-plugin-bigbluebutton#99]
Good morning,

is it somehow possible to re-publish the recordings? I want the trigger the publishing event to refresh all or at least some post by the plugin.

Thanks in advance!

**Comment by harshilsharma63** [comment]
@greatfireball what exactly do you mean by republishing?

**Comment by harshilsharma63** [comment]
Closing this for now. Feel free to re-open if you still face the issue.
